# Generated by Django 2.0.4 on 2018-06-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='kris_url',
            field=models.URLField(default='http://mykris.sqlview.com:8080/KRIS'),
        ),
    ]
